spring:
  profiles:
    active: prod
  application:
    name: coltranaidesktop
  datasource:
    url: jdbc:sqlite:${user.home}/.coltranai/coltranic.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
  ai:
    engine:
      port: ${OLLAMA_PORT:11435}
    ollama:
      base-url: http://localhost:${spring.ai.engine.port}
      chat: 
        options: 
          model: llama3.2
    chat:
      memory:
        jdbc:
          initialize-schema: never

